# Generated by Django 4.2.7 on 2026-02-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('tools', models.CharField(help_text='e.g. Ps • Ai • Ae • Pr', max_length=255)),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('portfolio_link', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['order', 'name'],
            },
        ),
    ]
