# Generated by Django 4.2.7 on 2026-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience',
            field=models.CharField(blank=True, help_text='e.g. 5+ Years Experience', max_length=100, null=True),
        ),
    ]
