# Generated by Django 4.2.7 on 2026-03-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_studentwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwork',
            name='image',
        ),
        migrations.AddField(
            model_name='studentwork',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', help_text='Main preview image for the card', upload_to='student_work/thumbnails/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_work/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aboutus.studentwork')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
